.PYONY: all, clean

all: 1-test 2-test 3-test \
	4-test 5-test 6-test

1-test: ../src/lib.o
2-test: ../src/lib.o
3-test: ../src/lib.o
4-test: ../src/lib.o
5-test: ../src/lib.o
6-test: ../src/lib.o

clean:
	rm -rf 1-test 2-test 3-test 4-test 5-test 6-test ../src/lib.o
