.PYONY: clean

LDLIBS = -lGLEW -lglfw -lGL -lm

hello-window: hello-window.c

hello-triangle: hello-triangle.c

hello-square: hello-square.c

animation-triangle: animation-triangle.c

colored-triangle: colored-triangle.c

clean:
	rm -rf hello-window \
		hello-triangle \
		hello-square \
		animation-triangle \
		colored-triangle
