.PYONY: clean

LDLIBS = -lGLEW -lglfw -lGL -lX11 -lpthread -lXrandr -lXi

hello-window: hello-window.c

hello-triangle: hello-triangle.c

hello-square: hello-square.c

clean:
	rm -rf hello-window \
		hello-triangle \
		hello-square
