.PYONY: clean

CC = gcc
LDLIBS = -lglut -lGLU -lGL -lm

hello: hello.c

animation: animation.c

smooth: smooth.c

cube: cube.c

clip: clip.c

robot: robot.c

unproject: unproject.c

light: light.c

blendeqn: blendeqn.c

alpha: alpha.c

alpha3D: alpha3D.c

clean:
	rm -rf hello animation smooth cube clip planet robot unproject light blendeqn alpha alpha3D
