create database data;
use data;
create table tb (i int, f float, s string);
select * from tb where i==1 || j==2 && k!=3;
insert into tb values(1, 1.0, "string");
select * from tb where i==1;
select * from tb where f==1.0;
select * from tb where s=="string";
select * from tb where i==2 && f==1.0;
select * from tb where i==2 || f==2.0 && s == "string";
select * from tb where i==2 || f==1.0;
select * from tb where i==1&&f==2.0 || s=="string";
select i from tb where i==1&&f==2.0 || s=="string";
